sudo: required
language: java
dist: trusty

addons:
  chrome: stable

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
cache:
  directories:
  - $HOME/.m2
      
script: mvn test -B

before_script:
  - whereis google-chrome-stable
  - whereis chromedriver
  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - ashkan@binary.com
      - mohammad@binary.com
      - bijan@binary.com
      - ridho@binary.com
      - dmytro@binary.com
      - ehtesham@binary.com
      - munsei@binary.com
      - negar@binary.com
      - kelly@binary.com
    on_success: never
    on_failure: always